# Site Settings
title: leo's blog | A blog for leo
email: wangliyao518@gmail.com
description: Some text about your blog.
baseurl: "/web" # the subpath of your site, e.g. /blog
url: "http://wangliyao518.github.io/web/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: leo
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: wangliyao518
facebook_username: wangliyao518
twitter_username: wangliyao518
instagram_username: wangliyao518
linkedin_username: wangliyao518
medium_username: wangliyao518

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
